### ISSUE TITLE
Compatibility with themes

### ISSUE THREAD

**Issue by imeed166** [liamcain/obsidian-lapel#1]
Just like the indentation guides plugin, it would be nice to have a style setting option to adjust the position of the `H1/2/3` icon, to help with compatibility when using other themes.

**Comment by liamcain** [comment]
Hi, could you provide a bit more context? I'm not familiar with the position adjustments offered by indentation guides, and when I tried out different themes (Primary, Minimal, YinYang, California Coast), it looks to be in the correct position to me.

**Comment by mayurankv** [comment]
This currently does not work nicely with a small gutter and line numbering on. It would be good if this didn't intrude onto text.

**Comment by yoghurtdewdew** [comment]
Is there any progress? I use Minimal for theme, I found it could not appear correctly as https://github.com/liamcain/obsidian-lapel/issues/18#issuecomment-1668833428 the header always overlap with text.

**Comment by liamcain** [comment]
I believe this is fixed now. Let me know if there are still issues.

**Comment by danieltomasz** [comment]
it seem there are issue with minimal theme :(
