### ISSUE TITLE
Positioning In Minimal 5.2.8 Is Off

### ISSUE THREAD

**Issue by takeo** [liamcain/obsidian-lapel#12]
In Minimal 5.2.8 (latest at the time of this issue) the positioning of the lapel gutter is all the way to the left instead of right outside of the editor area:

![CleanShot 2022-05-21 at 16 45 15@2x](https://user-images.githubusercontent.com/23/169672494-66f06f81-fb93-4d1b-a280-006275a4710c.png)

It seems to be ok in other themes, so it must be a conflict with Minimal. I poked around in the inspector but I'm too rusty to have identified anything that could be causing it.

**Comment by 23727** [comment]
I am also experiencing this with the minimal theme when readable line length is toggled on. I originally toggled off all plug-ins and snippets but found no conflicts. Like @takeo, I found that other themes seemed to work correctly.

**Comment by isle9** [comment]
Yeah, seems to be a problem with the Minimalist theme.

**Comment by takeo** [comment]
> This seems to be intended behavior in minimal theme as of [5.2.0](https://github.com/kepano/obsidian-minimal/releases/tag/5.2.0#:~:text=Plugins%20such%20as%20Lapel%2C%20are%20by%20extension%20moved%20to%20the%20left%20edge)

well... damn. ok, closing the issue.
