### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by masonc15** [liamcain/obsidian-lapel#15]
Hello,

I recently started getting an error upon Obsidian startup where it says "Failed to load plugin lapel".  I'm not sure what might have changed.  I am using Windows and Obsidian version 0.14.15.  Here is the console log when I try to enable lapel:

```
Plugin failure: lapel TypeError: Class extends value undefined is not a constructor or null
    at anonymous (plugin:lapel:6:666)
    at t.<anonymous> (app.js:1:1517585)
    at app.js:1:235084
    at Object.next (app.js:1:235189)
    at s (app.js:1:233928)
```

Any help would be appreciated.  Love the plugin, thanks!

**Comment by liamcain** [comment]
Hi, can you let me know what version of the plugin you're using?

**Comment by masonc15** [comment]
Version 0.1.0.

I have used "Check for updates" to make sure all plugins are updated to the most recent version.

**Comment by liamcain** [comment]
That's strange, you shouldn't have been able to install v0.1.0. That is only meant to be used with Obsidian v0.15+.

If you uninstall the plugin and try reinstalling, can you see if you get put on version 0.0.3 again?

**Comment by masonc15** [comment]
OK, so I think I kinda figured out what the issue was.  I use Obsidian Sync and my main Desktop instance of Obsidian was set to receive Insider Builds, while my other instances were not.  I'm not sure if this affects community plugin versions, but I thought it could be relevant.  

Anyway, I uninstalled Lapel on all instances and after reinstalling, it's on version 0.0.3 as it should be.  However, if I press the Update or even the general "Check for updates" button, it prompts a Lapel update to v0.1.0.  So it's fixed for now but I will just have to be careful with bulk plugin updates from now on.  Thanks for the help.
