### ISSUE TITLE
Any chance to update plugin to be fully compatible with 1.0?

### ISSUE THREAD

**Issue by danieltomasz** [liamcain/obsidian-lapel#17]
With the changes to themes, the plugin doesnt fit that well as before.

**Comment by FriedrichStein** [comment]
Would love to see an update! :) 
The proper alignment broke recently for me and now it got hard to discern headinglevels for me 🫤
But otherwise great plug-in! Thanks!!

**Comment by liamcain** [comment]
Updated with some compatibility fixes. Let me know if there's anything specific that's not working and I'll try to address.
