### ISSUE TITLE
Header labels overlap text

### ISSUE THREAD

**Issue by meeebee** [liamcain/obsidian-lapel#18]
On the default theme, the header labels overlap the text like so.  It is the same for the other themes I have: Atom, Blue Topaz, Nord, Things, Red Graphite.
![image](https://user-images.githubusercontent.com/72706006/196791110-77b71033-b368-4ca1-9bf3-640c38709e7b.png)

Only on the Minimal theme does it appear correctly.
![image](https://user-images.githubusercontent.com/72706006/196791280-7167e2c8-e4d4-49ad-bc55-b0514d6f5254.png)

I'm unsure what to change to get the other themes with the correct header label placement.

**Comment by Sheldontao** [comment]
I have the same issue! Please, solve!

**Comment by yoghurtdewdew** [comment]
I have the same issue! Please, solve!

And as mentioned in https://github.com/liamcain/obsidian-lapel/issues/18#issue-1415510861 , on the Minimal theme it does not appear correctly.

<img width="431" alt="image" src="https://github.com/liamcain/obsidian-lapel/assets/63794438/b0897d0b-d1c1-4693-bf17-4ab523f1106f">
<img width="383" alt="image" src="https://github.com/liamcain/obsidian-lapel/assets/63794438/d8677df6-9f87-4e28-9512-d786d0132bdd">

**Comment by liamcain** [comment]
v0.1.4 is now available and should have slightly better theme compatibility. Let me know if this is still an issue.
