### ISSUE TITLE
[BUG] Lapel deletes all content under a heading, if the heading level is changed while the heading is folded.

### ISSUE THREAD

**Issue by MSBack** [liamcain/obsidian-lapel#19]
Steps to reproduce:
1. Enable Fold heading under Settings/Editor/Fold heading
2. Fold a heading
3. Change the heading level using Lapel

All the content under the heading is now gone, and there is nothing to unfold. This is obviously extremely problematic.

**Comment by ShengYULAN** [comment]
I want to kill this develop,he almost make me lost all my content.

**Comment by MSBack** [comment]
@liamcain Have to seen this? It's quite a serious bug.

**Comment by liamcain** [comment]
Thanks for the bump. Sorry I missed this bug report before. I just pushed a fix for this in v0.1.1
