### ISSUE TITLE
This is really helpful but I cannot find it within Obsidian Plugins?

### ISSUE THREAD

**Issue by cocoonkid** [liamcain/obsidian-lapel#2]
This is really helpful but I cannot find it within Obsidian Plugins?

Thanks :-)

**Comment by liamcain** [comment]
Hi, it's been submitted to the plugin gallery but it's still pending review from the Obsidian team. They usually do plugin reviews every 7-10 days so it might be a little while!

If you'd like to install it before then, the easiest way to do so is with BRAT: [TfTHacker/obsidian42-brat](https://github.com/TfTHacker/obsidian42-brat)

**Comment by cocoonkid** [comment]
Thanks!!
