### ISSUE TITLE
Not working in Obsidian 1.3.4

### ISSUE THREAD

**Issue by merlinuwe** [liamcain/obsidian-lapel#20]
Thanks for your great plugin.

When I use it in Obsidian 1.3.4 and with Minimal Theme, it shows the numbers only, when I change to button position. (Regardless of the direction.)

![image](https://github.com/liamcain/obsidian-lapel/assets/4138869/483a65e8-a008-4af3-b5b9-63b985ca1485)

![image](https://github.com/liamcain/obsidian-lapel/assets/4138869/119c2f9d-0b7a-4292-9e3d-3de0f9493a97)

When I scroll a little bit, the H2 dissapears.

When I use Standard Theme, it nevers shows the header numbers.

What can I do to get it running?

**Comment by gooooloo** [comment]
Not working in Obsidian 1.3.5 neither

**Comment by liamcain** [comment]
Updated. Is this still an issue?

**Comment by merlinuwe** [comment]
The problem is still there.
Windows 10, Obsidian 1.6.5

Can I help you with testing?

**Comment by StrangePeanut** [comment]
It works for me, thanks!

@merlinuwe note that it doesn't work in source mode.

**Comment by merlinuwe** [comment]
Hm, the plugin works not for me. When I scroll the numbers out of the view (edit mode) and back they aren't there anymore.

Then I use the lapel switch to see them again.

This is endless reproducable.

(Now I have tested on android 11.)

**Comment by StrangePeanut** [comment]
> When I scroll the numbers out of the view (edit mode) and back they aren't there anymore.

@merlinuwe oh that's interesting. I can't replicate that behaviour on PC and mobile on my end.

(I just wish that it didn't shift all content to the right especially on mobile but that's a different issue altogether.)

**Comment by liamcain** [comment]
@merlinuwe Can you share the output when you run the command "show debug info"? It should show a list of plugins and other info that will help me debug

**Comment by merlinuwe** [comment]
> @merlinuwe Can you share the output when you run the command "show debug info"? It should show a list of plugins and other info that will help me debug

Sure. You're right, it must have something to do with the plugins, because in an empty test vault on Windows 10 your plugin runs.

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.7.0
	Snippets enabled: 43
	Restricted mode: off
	Plugins installed: 158
	Plugins enabled: 65
		1: Set View Mode per Note v1.0.3
		2: Advanced Tables v0.21.0
		3: Android nomedia v0.1.0
		4: Auto Link Title v1.5.4
		5: Beautitab v1.6.1
		6: Better Export PDF v1.8.3
		7: Commander v0.5.1
		8: Colored Tags Wrangler v0.19.3
		9: Copy document as HTML v0.8.1
		10: Creases v0.7.0
		11: Custom Classes v2.6.1
		12: Dictionary v2.22.0
		13: Editing Toolbar v2.4.16
		14: Editor Commands Remap v1.0.2
		15: Editor Syntax Highlight v0.1.3
		16: Enhancing Export v1.10.6
		17: Excel to Markdown Table v0.4.0
		18: Export Image plugin v2.3.10
		19: File Explorer Note Count v1.2.2
		20: Google Calendar v1.10.14
		21: Linter v1.25.0
		22: Local Backup v0.1.7
		23: markdown export v1.0.23
		24: Natural Language Dates v0.6.2
		25: Navigate Cursor History v1.1.0
		26: Number Headings v1.16.0
		27: Omnisearch v1.23.1
		28: Paste image rename v1.6.1
		29: Quick Explorer v0.2.8
		30: Quiet Outline v0.3.36
		31: Recent Files v1.4.1
		32: Settings Management v1.0.5
		33: Sheet Plus v1.3.1
		34: Show Current File Path v0.5.2
		35: Sortable v0.3.1
		36: Status Bar Organizer v2.0.2
		37: Style Settings v1.0.8
		38: Symbols Prettifier v1.1.4
		39: Tag Wrangler v0.6.1
		40: Tasks v7.6.1
		41: Templater v2.3.3
		42: Text Extractor v0.5.2
		43: Todo sort v1.0.0
		44: Translate v1.4.9
		45: Typing Transformer v0.4.0
		46: Vault Changelog v0.1.0
		47: Vault Statistics v0.1.3
		48: Webpage HTML Export v1.8.01
		49: Link Converter v0.1.6
		50: Date Inserter v0.3.3
		51: Dataview v0.5.67
		52: Desmos v0.6.8
		53: Plugins Annotations v1.4.0
		54: Color Palette v2.13.7
		55: Docxer v2.0.1
		56: Supercharged Links v0.12.1
		57: Query Control v0.6.0
		58: Share my plugin list v0.3.3
		59: Note Toolbar v1.9.3
		60: Refresh Preview v1.3.0
		61: Printsidian v0.1.0
		62: Quick Switcher++ v4.4.0
		63: Shell commands v0.22.0
		64: Advanced URI v1.41.0
		65: Lapel v0.1.5
