### ISSUE TITLE
Tables in 1.5 don´t show the icon to sort rows

### ISSUE THREAD

**Issue by javiavid** [liamcain/obsidian-lapel#21]
When activating the plugin, the icon to change the order of rows in a table with obsidian version 1.5 does not appear.

<img width="158" alt="image" src="https://github.com/liamcain/obsidian-lapel/assets/7627504/f80b35f9-9f4d-49fa-a4c7-81b65ff3ba96">

**Comment by liamcain** [comment]
I think this was fixed with an Obsidian update, let me know if this is still an issue with version 1.1.3 of Lapel and I'll reopen.

**Comment by javiavid** [comment]
It's solved, thanks
