### ISSUE TITLE
Will insert a gutter at the beginning of the current editing table cell from Obsidian v.1.5.*

### ISSUE THREAD

**Issue by lethefrost** [liamcain/obsidian-lapel#22]
The plugins `lapel` and `obsidian42-strange-new-worlds` both insert a gutter to a cell, so the current workaround is to make sure both are turned off if you want to remove the gutter. Waiting for a fix. Thank you for developing and maintaining this plugin! ❤️

**Comment by rotane** [comment]
A quick fix is to add this line to your CSS snippets:

`.table-cell-wrapper .cm-gutters { display: none !important; }`

**Comment by liamcain** [comment]
Thanks! Fixed in 0.1.5
