### ISSUE TITLE
The plugin not work

### ISSUE THREAD

**Issue by chumido98** [liamcain/obsidian-lapel#3]
I'm using Minimal theme, but after install and enable plugin, not thing happen, what did i miss? thank you very much.

**Comment by liamcain** [comment]
Hi @chumido98 can you make sure that you're using Live Preview and that "Use legacy editor" is turned off in the settings?

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/693981/159723508-3333ecdd-2dfe-4285-8e93-6c5005e748f1.png">

Lapel only works in Live Preview mode in the new editor.

**Comment by chumido98** [comment]
It's working now, thank you very much.
