### ISSUE TITLE
[Feature Request] Allow Icon Change

### ISSUE THREAD

**Issue by ocreturner** [liamcain/obsidian-lapel#7]
After seeing your metadata icon for H6 i realized that it would be a great addition to allow it to be changed with a right click menu for all header icons. maybe even in the settings if its easier

**Comment by liamcain** [comment]
There's information in the readme about how to change this with a small CSS snippet: https://github.com/liamcain/obsidian-lapel#-customization

**Comment by Obadiahcruz** [comment]
ah! yea i got it to work with using !important with that snippet
