### ISSUE TITLE
[Feature Request] Allow icon positioning 

### ISSUE THREAD

**Issue by ocreturner** [liamcain/obsidian-lapel#8]
there are times when headers are resized and it causes the placement of the header indicators to seem misplaced 

the indentation plugin does this well by allowing us to move them inside of the style settings plugin

**Comment by liamcain** [comment]
Can you provide a screenshot and maybe more information about what themes are causing issues?

**Comment by Obadiahcruz** [comment]
They tend to move with the minimal theme if i want the headers to be bigger than the default minimal theme. you can see that the h3 tends to move. when i use css to move the h3 to not make those jumps then the others sometimes jump 

https://user-images.githubusercontent.com/22825246/160173990-322341fa-c5e7-4375-8ed7-240ea9f86deb.mov

**Comment by liamcain** [comment]
@Obadiahcruz can you try updating your version of Minimal? For the shifting, I actually submitted a fix to the theme that was added [sometime last week](https://github.com/kepano/obsidian-minimal/commit/eb2957ddffa6ae53c2118f2a4a62e1ef549db621).

**Comment by Obadiahcruz** [comment]
alright ill give it a shot !

**Comment by liamcain** [comment]
I think this is fixed, I can reopen if users are still having issues.
